// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Belt_Int = require("rescript/lib/js/belt_Int.js");
var Belt_Array = require("rescript/lib/js/belt_Array.js");
var Belt_Option = require("rescript/lib/js/belt_Option.js");

var input = Fs.readFileSync("input/Week2/Day2Input.sample.txt", "utf8");

function getInt(arr, idx) {
  return Belt_Option.getExn(Belt_Int.fromString(Belt_Array.getExn(arr, idx)));
}

function parsePolicy(x) {
  var arr = x.split(":");
  var policy = Belt_Array.getExn(arr, 0);
  var target = Belt_Array.getExn(arr, 1).trim();
  var arrPolicy = policy.split(" ");
  var arrNum = Belt_Array.getExn(arrPolicy, 0).split("-");
  var str = Belt_Array.getExn(arrPolicy, 1);
  return [[
            getInt(arrNum, 0),
            getInt(arrNum, 1),
            str,
            target
          ]];
}

function checkValid(x) {
  return 1;
}

console.log("part1 result :: ");

console.log(Belt_Array.reduce(Belt_Array.reduce(input.split("\n"), [], (function (acc, x) {
                return Belt_Array.concat(acc, parsePolicy(x));
              })), 0, (function (acc, x) {
            return acc + 1 | 0;
          })));

exports.input = input;
exports.getInt = getInt;
exports.parsePolicy = parsePolicy;
exports.checkValid = checkValid;
/* input Not a pure module */
