// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Belt_Int = require("rescript/lib/js/belt_Int.js");
var Belt_Array = require("rescript/lib/js/belt_Array.js");

var input = Fs.readFileSync("input/Week1/Day7Input.sample.txt", "utf8");

function removeStr(x) {
  return x.replace(/bags|bag|[0-9]|\./g, "").trim();
}

var arrInput = input.split("\n");

function getList(key) {
  return Belt_Array.getExn(Belt_Array.keep(arrInput, (function (x) {
                      return x.indexOf(key) > -1;
                    })), 0).split("contain");
}

function parseContain(x) {
  var cnt = Belt_Int.fromString(x.trim());
  if (cnt !== undefined) {
    return {
            name: removeStr(x).trim(),
            cnt: cnt,
            nodes: []
          };
  }
  
}

exports.input = input;
exports.removeStr = removeStr;
exports.arrInput = arrInput;
exports.getList = getList;
exports.parseContain = parseContain;
/* input Not a pure module */
